version: '3'
services:
  ts-social-db:
    image: postgres:latest
    ports:
      - "5433:5432"
    volumes:
      - data:/var/lib/postgresql/data
  ts-social-test-db:
    image: postgres:latest
    ports:
      - "5434:5432"
    volumes:
      - test_data:/var/lib/postgresql/data
volumes:
  data:
  test_data: